#!/bin/bash

# version 20161105

#inicializace
repo_info=""

# zjisti pripadny git branch
if git branch > /dev/null 2>&1; then
    git_branchname=`git branch | grep "^*" | sed 's/^* //'`
    repo_info="${repo_info}[${git_branchname}]"
fi

# pripadne zjisti svn revizi
if svn info > /dev/null 2>&1; then
    svn_revision=`svn info | grep "^Revision:" | sed 's/Revision/svn rev/'`
    repo_info="${repo_info}[${svn_revision}]"
fi

echo "${repo_info}"
